services:
  - type: web
    name: chatpdf-server
    runtime: docker
    # Tells Render to use the Dockerfile in your repository
    dockerfilePath: ./Dockerfile
    # Tells Render to automatically use the port from the Dockerfile
    autoDeploy: false
    envVars:
      - key: PORT
        value: 8000
      - key: GOOGLE_API_KEY
        # This ensures the value is taken from your secret settings
        sync: false
